#!/bin/sh
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
ARCH=${FUTO_ARCH:-aarch64}
BUILD=${FUTO_BUILD_DIR:-$ROOT/build/$ARCH}
SHARED_ROOT=${FUTO_SHARED_ROOT:-$ROOT/../shared}
QT_SOURCE=${FUTO_QT_SOURCE:-$SHARED_ROOT/qtbase-5.6.3}
TARGET_LIB_ROOT=${FUTO_TARGET_LIB_ROOT:-${FUTO_PHONE_LIB_ROOT:-$SHARED_ROOT/futo-phone-sysroot}}
TARGET_SYSROOT=${FUTO_TARGET_SYSROOT:-}
if [ -n "$TARGET_SYSROOT" ]; then
    TARGET_SYSROOT_OPTION="--sysroot=$TARGET_SYSROOT"
else
    TARGET_SYSROOT_OPTION=
fi
CROSS_ROOT=${FUTO_CROSS_ROOT:-}
case "$ARCH" in
    aarch64) TOOL_PREFIX=aarch64-linux-gnu ;;
    armv7hl) TOOL_PREFIX=armv7hl-meego-linux-gnueabi ;;
    i486) TOOL_PREFIX=i486-meego-linux-gnu ;;
    *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac
if [ -n "$CROSS_ROOT" ]; then
    DEFAULT_CXX="$CROSS_ROOT/usr/bin/$TOOL_PREFIX-g++"
    DEFAULT_STRIP="$CROSS_ROOT/usr/bin/$TOOL_PREFIX-strip"
else
    DEFAULT_CXX="$TOOL_PREFIX-g++"
    DEFAULT_STRIP="$TOOL_PREFIX-strip"
fi
CXX=${FUTO_CXX:-${CXX_AARCH64:-$DEFAULT_CXX}}
STRIP=${FUTO_STRIP:-${STRIP_AARCH64:-$DEFAULT_STRIP}}
HOST_MOC=${FUTO_HOST_MOC:-moc}
SOURCE=$QT_SOURCE/src/plugins/platforminputcontexts/compose
WRAPPER_SOURCE=$ROOT/hardware/compose/futo_maliit_compose_wrapper.cpp
OUTPUT=$BUILD/qt-compose-plugin
HEADER_ROOT=$BUILD/qt-compose-includes
INCLUDE=${FUTO_QT_INCLUDE_ROOT:-$HEADER_ROOT/include}

if command -v "$CXX" >/dev/null 2>&1; then
    CXX=$(command -v "$CXX")
else
    test -x "$CXX"
fi
if command -v "$STRIP" >/dev/null 2>&1; then
    STRIP=$(command -v "$STRIP")
else
    test -x "$STRIP"
fi
if command -v "$HOST_MOC" >/dev/null 2>&1; then
    HOST_MOC=$(command -v "$HOST_MOC")
else
    test -x "$HOST_MOC"
fi

for required in \
    "$SOURCE/qcomposeplatforminputcontextmain.cpp" \
    "$SOURCE/qcomposeplatforminputcontext.cpp" \
    "$SOURCE/generator/qtablegenerator.cpp" \
    "$WRAPPER_SOURCE" \
    "$ROOT/hardware/compose/futo-maliit-compose-wrapper.json" \
    "$TARGET_LIB_ROOT/libQt5Core.so.5.6.3" \
    "$TARGET_LIB_ROOT/libQt5Gui.so.5.6.3" \
    "$TARGET_LIB_ROOT/libxkbcommon.so.0.0.0"; do
    test -s "$required"
done

if [ -z "${FUTO_QT_INCLUDE_ROOT:-}" ] && \
        [ ! -s "$INCLUDE/QtGui/5.6.3/QtGui/qpa/qplatforminputcontextplugin_p.h" ]; then
    rm -rf "$HEADER_ROOT"
    mkdir -p "$HEADER_ROOT"
    perl "$QT_SOURCE/bin/syncqt.pl" "$QT_SOURCE" \
        -outdir "$HEADER_ROOT" -version 5.6.3 -copy -quiet
fi
if [ -z "${FUTO_QT_INCLUDE_ROOT:-}" ]; then
    # qconfig.h is generated by Qt's configure step and is therefore not
    # emitted by syncqt. Reuse the captured target-matched configuration.
    cp "$QT_SOURCE/include/QtCore/qconfig.h" "$INCLUDE/QtCore/qconfig.h"
    cp "$QT_SOURCE/include/QtCore/qfeatures.h" "$INCLUDE/QtCore/qfeatures.h"
fi

rm -rf "$OUTPUT"
mkdir -p "$OUTPUT"
"$HOST_MOC" -DQT_PLUGIN -DQT_SHARED \
    -I"$INCLUDE" \
    -I"$INCLUDE/QtCore" \
    -I"$INCLUDE/QtCore/5.6.3" \
    -I"$INCLUDE/QtCore/5.6.3/QtCore" \
    -I"$INCLUDE/QtGui" \
    -I"$INCLUDE/QtGui/5.6.3" \
    -I"$INCLUDE/QtGui/5.6.3/QtGui" \
    "$SOURCE/qcomposeplatforminputcontextmain.cpp" \
    -o "$OUTPUT/qcomposeplatforminputcontextmain.moc"
"$HOST_MOC" -DQT_PLUGIN -DQT_SHARED \
    -I"$INCLUDE" \
    -I"$INCLUDE/QtCore" \
    -I"$INCLUDE/QtCore/5.6.3" \
    -I"$INCLUDE/QtCore/5.6.3/QtCore" \
    -I"$INCLUDE/QtGui" \
    -I"$INCLUDE/QtGui/5.6.3" \
    -I"$INCLUDE/QtGui/5.6.3/QtGui" \
    "$SOURCE/qcomposeplatforminputcontext.h" \
    -o "$OUTPUT/moc_qcomposeplatforminputcontext.cpp"
"$HOST_MOC" -DQT_PLUGIN -DQT_SHARED \
    -I"$INCLUDE" \
    -I"$INCLUDE/QtCore" \
    -I"$INCLUDE/QtCore/5.6.3" \
    -I"$INCLUDE/QtCore/5.6.3/QtCore" \
    -I"$INCLUDE/QtGui" \
    -I"$INCLUDE/QtGui/5.6.3" \
    -I"$INCLUDE/QtGui/5.6.3/QtGui" \
    -I"$ROOT/hardware/compose" \
    "$WRAPPER_SOURCE" \
    -o "$OUTPUT/futo_maliit_compose_wrapper.moc"

compile() {
    source_file=$1
    object_file=$2
    "$CXX" $TARGET_SYSROOT_OPTION -std=c++11 -O2 -DNDEBUG -fPIC \
        -DQT_PLUGIN -DQT_SHARED -DQT_NO_DEBUG '-DX11_PREFIX="/usr"' \
        -I"$OUTPUT" \
        -I"$SOURCE" -I"$SOURCE/generator" \
        -I"$INCLUDE" \
        -I"$INCLUDE/QtCore" \
        -I"$INCLUDE/QtCore/5.6.3" \
        -I"$INCLUDE/QtCore/5.6.3/QtCore" \
        -I"$INCLUDE/QtGui" \
        -I"$INCLUDE/QtGui/5.6.3" \
        -I"$INCLUDE/QtGui/5.6.3/QtGui" \
        -I"$QT_SOURCE/mkspecs/linux-g++" \
        -I"$QT_SOURCE/src/3rdparty/xkbcommon" \
        -c "$source_file" -o "$object_file"
}

compile "$SOURCE/qcomposeplatforminputcontextmain.cpp" \
    "$OUTPUT/qcomposeplatforminputcontextmain.o"
compile "$SOURCE/qcomposeplatforminputcontext.cpp" \
    "$OUTPUT/qcomposeplatforminputcontext.o"
compile "$OUTPUT/moc_qcomposeplatforminputcontext.cpp" \
    "$OUTPUT/moc_qcomposeplatforminputcontext.o"
compile "$SOURCE/generator/qtablegenerator.cpp" \
    "$OUTPUT/qtablegenerator.o"
compile "$WRAPPER_SOURCE" "$OUTPUT/futo_maliit_compose_wrapper.o"

"$CXX" $TARGET_SYSROOT_OPTION -shared \
    -Wl,-soname,libcomposeplatforminputcontextplugin.so \
    -Wl,--allow-shlib-undefined \
    "$OUTPUT/qcomposeplatforminputcontextmain.o" \
    "$OUTPUT/qcomposeplatforminputcontext.o" \
    "$OUTPUT/moc_qcomposeplatforminputcontext.o" \
    "$OUTPUT/qtablegenerator.o" \
    -L"$TARGET_LIB_ROOT" \
    -l:libQt5Gui.so.5.6.3 \
    -l:libQt5Core.so.5.6.3 \
    -l:libxkbcommon.so.0.0.0 \
    -lpthread -ldl \
    -o "$BUILD/libcomposeplatforminputcontextplugin.so"
"$STRIP" "$BUILD/libcomposeplatforminputcontextplugin.so"

"$CXX" $TARGET_SYSROOT_OPTION -shared \
    -Wl,-soname,libafutomaliitcomposewrapper.so \
    -Wl,--allow-shlib-undefined \
    "$OUTPUT/futo_maliit_compose_wrapper.o" \
    -L"$TARGET_LIB_ROOT" \
    -l:libQt5Gui.so.5.6.3 \
    -l:libQt5Core.so.5.6.3 \
    -lpthread -ldl \
    -o "$BUILD/libafutomaliitcomposewrapper.so"
"$STRIP" "$BUILD/libafutomaliitcomposewrapper.so"

file "$BUILD/libcomposeplatforminputcontextplugin.so" \
    "$BUILD/libafutomaliitcomposewrapper.so"
